context:
  version: "7.2.1"

package:
  name: ionic-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@ionic/cli/-/cli-${{ version }}.tgz
  sha256: 97c5e388766f56e16e47b5eaa3ab233d1ff4cc8add5f0cd906b27e3ea6e29585

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - ionic --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A tool for creating and developing Ionic Framework mobile apps.
  homepage: https://ionicframework.com/
  repository: hhttps://github.com/ionic-team/ionic-cli

extra:
  recipe-maintainers:
    - danielnachun
